# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
Rcpp_quilt_test_doubler <- function(a) {
    .Call('_QUILT_Rcpp_quilt_test_doubler', PACKAGE = 'QUILT', a)
}

