# Run CI for R using https://eddelbuettel.github.io/r-ci/
# This file is a slight variant by running a matrix of containers

name: R-CMD-check

on:
  push:
    branches: [master, zilong, nipt]
  pull_request:
    branches: [master, zilong, nipt]

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - name: Clean up temp files
        if: runner.os != 'Windows'
        run: rm -rf /var/folders/* || true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check
          cache-version: 2
          working-directory: ./QUILT

      - uses: r-lib/actions/check-r-package@v2
        with:
          working-directory: ./QUILT
          args: 'c("--no-manual", "--no-tests", "--as-cran")'
          error-on: '"error"'
          upload-snapshots: true
