name: CI

on:
  push:
    branches: [master, zilong, nipt]
  pull_request:
    branches: [master, zilong, nipt]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test-all:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest,   r: 'release'}
          - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
          
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - name: Install dependencies
        run: |
          export MAKE="make -j6"
          sudo bash ./scripts/install-dependencies.sh
          sudo ./scripts/install-r-dependencies.R

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          working-directory: ./QUILT
          extra-packages: |
            any::proftools
            any::devtools
            any::testthat
            any::optparse
            any::rcmdcheck
          cache-version: 2

      - uses: r-lib/actions/check-r-package@v2
        with:
          working-directory: ./QUILT
          args: 'c("--no-manual", "--as-cran")'
          error-on: '"error"'
          upload-snapshots: true

      - name: Test the build
        run: ./scripts/build-and-install.R
        
      - name: Test README
        run: ./scripts/test-readme.sh

      - name: Test the CLI
        run: ./scripts/test-cli.R
 
      - name: HLA test
        run: ./scripts/run_hla_example.sh
