name: CI

on:
  push:
    branches: [master, zilong, nipt]
  pull_request:
    branches: [master, zilong, nipt]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test-all:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest,   r: 'release'}
          - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
          
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      
      - name: Build and Install
        run: |
          export MAKE="make -j6"
          sudo apt-get update -y
          sudo apt-get install -qy build-essential libbz2-dev libcurl4-openssl-dev libxml2-dev libssl-dev zlib1g-dev liblzma-dev libdeflate-dev libncurses5-dev curl autoconf lzma-dev 
          sudo apt-get install -qy r-base r-cran-devtools
          sudo bash ./scripts/install-dependencies.sh
          sudo Rscript ./scripts/install-r-dependencies.R
          sudo Rscript ./scripts/build-and-install.R

      - uses: r-lib/actions/check-r-package@v2
        with:
          working-directory: ./QUILT
          args: 'c("--no-manual", "--as-cran")'
          error-on: '"error"'
          upload-snapshots: true

      - name: Test the build
        run: ./scripts/build-and-install.R
        
      - name: Test README
        run: ./scripts/test-readme.sh

      - name: Test the CLI
        run: ./scripts/test-cli.R
 
      - name: HLA test
        run: ./scripts/run_hla_example.sh
